### ISSUE TITLE
Shared App Permission Issue

### ISSUE THREAD

**Issue by qianyuanzhu** [OSC/bc_osc_galaxy#4]
Regenerating static plugin directories.
Traceback (most recent call last):
  File "./scripts/plugin_staging.py", line 34, in <module>
    link_up_static(f)
  File "./scripts/plugin_staging.py", line 19, in link_up_static
    shutil.rmtree(dest)
  File "/usr/lib64/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/users/PZS0002/azhu/awesim/share/galaxy3/galaxy/static/plugins/interactive_environments/askomics/static/js/askomics.js'

**Comment by qianyuanzhu** [comment]
https://github.com/OSC/galaxy/blob/67bb91348bb26584b83592542424d329714d6b47/scripts/plugin_staging.py#L10-L27

**Comment by qianyuanzhu** [comment]
The temporary fix is commenting out https://github.com/galaxyproject/galaxy/blob/5d1df57f7fda17fc24139ab8e7bb608d4d5c89a2/scripts/common_startup.sh#L251. As a result, users are not able to customize galaxy.
